// <auto-generated />
using System;
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace API.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("API.Entitites.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("API.Entitites.PrintEntities.FBOProduct", b =>
                {
                    b.Property<string>("BCWB_on_Box")
                        .HasColumnType("text");

                    b.Property<string>("Bar_User")
                        .HasColumnType("text");

                    b.Property<string>("Barcode1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Order_Id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("Print_Time")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Printed")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Printer_Name")
                        .HasColumnType("text");

                    b.Property<string>("Quant")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Request")
                        .HasColumnType("text");

                    b.Property<string>("Sector")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Sticker1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Sticker2")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Template_Name")
                        .HasColumnType("text");

                    b.HasKey("BCWB_on_Box");

                    b.HasIndex("Order_Id");

                    b.ToTable("FBO");
                });

            modelBuilder.Entity("API.Entitites.PrintEntities.FBSProduct", b =>
                {
                    b.Property<string>("SHKWB")
                        .HasColumnType("text");

                    b.Property<string>("Art")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Art_Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Bar_User")
                        .HasColumnType("text");

                    b.Property<string>("CodSalrus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Naim")
                        .HasColumnType("text");

                    b.Property<string>("Order_Id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Print_Time")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Printed")
                        .HasColumnType("text");

                    b.Property<string>("Printer_Name")
                        .HasColumnType("text");

                    b.Property<int>("Quant")
                        .HasColumnType("integer");

                    b.Property<string>("Request")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SHK1")
                        .HasColumnType("text");

                    b.Property<string>("SHK1C")
                        .HasColumnType("text");

                    b.Property<string>("SHK2")
                        .HasColumnType("text");

                    b.Property<string>("SHK3")
                        .HasColumnType("text");

                    b.Property<string>("Sticker1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Sticker2")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Template_Name")
                        .HasColumnType("text");

                    b.HasKey("SHKWB");

                    b.HasIndex("Order_Id");

                    b.ToTable("FBS");
                });

            modelBuilder.Entity("API.Entitites.PrintEntities.PrintOrder", b =>
                {
                    b.Property<string>("Order_Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("Order_Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Order_Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Order_Id");

                    b.ToTable("PrintOrders");
                });

            modelBuilder.Entity("API.Entitites.WBEntities.Income", b =>
                {
                    b.Property<int?>("incomeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("incomeId"));

                    b.Property<DateTime>("date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("dateClose")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("number")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("warehouseName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("incomeId");

                    b.ToTable("Incomes");
                });

            modelBuilder.Entity("API.Entitites.WBEntities.IncomeDetail", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("barcode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("incomeId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("lastChangeDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("nmId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<int>("quantity")
                        .HasColumnType("integer");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("totalPrice")
                        .HasColumnType("numeric");

                    b.HasKey("id");

                    b.HasIndex("incomeId");

                    b.ToTable("IncomeDetails");
                });

            modelBuilder.Entity("API.Entitites.WBEntities.Order", b =>
                {
                    b.Property<string>("gNumber")
                        .HasColumnType("text");

                    b.Property<DateTime>("date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("number")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("gNumber");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("API.Entitites.WBEntities.OrderDetail", b =>
                {
                    b.Property<decimal>("odid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("barcode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("brand")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("cancel_dt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("discountPercent")
                        .HasColumnType("integer");

                    b.Property<string>("gNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("incomeId")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<bool>("isCancel")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("lastChangeDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("nmId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("number")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("oblast")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("quantity")
                        .HasColumnType("integer");

                    b.Property<string>("sticker")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("subject")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("supplierArticle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("techSize")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("totalPrice")
                        .HasColumnType("numeric");

                    b.Property<string>("warehouseName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("odid");

                    b.HasIndex("gNumber");

                    b.HasIndex("incomeId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("API.Entitites.WBEntities.Sale", b =>
                {
                    b.Property<string>("saleID")
                        .HasColumnType("text");

                    b.Property<int>("IsStorno")
                        .HasColumnType("integer");

                    b.Property<string>("countryName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("finishedPrice")
                        .HasColumnType("numeric");

                    b.Property<decimal>("forPay")
                        .HasColumnType("numeric");

                    b.Property<int>("incomeID")
                        .HasColumnType("integer");

                    b.Property<bool>("isRealization")
                        .HasColumnType("boolean");

                    b.Property<bool>("isSupply")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("lastChangeDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("number")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("oblastOkrugName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("odid")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal?>("orderId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("priceWithDisc")
                        .HasColumnType("numeric");

                    b.Property<int>("promoCodeDiscount")
                        .HasColumnType("integer");

                    b.Property<string>("regionName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("spp")
                        .HasColumnType("integer");

                    b.Property<string>("warehouseName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("saleID");

                    b.HasIndex("odid");

                    b.ToTable("Sales");
                });

            modelBuilder.Entity("API.Entitites.PrintEntities.FBOProduct", b =>
                {
                    b.HasOne("API.Entitites.PrintEntities.PrintOrder", "PrintOrder")
                        .WithMany()
                        .HasForeignKey("Order_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PrintOrder");
                });

            modelBuilder.Entity("API.Entitites.PrintEntities.FBSProduct", b =>
                {
                    b.HasOne("API.Entitites.PrintEntities.PrintOrder", "PrintOrder")
                        .WithMany()
                        .HasForeignKey("Order_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PrintOrder");
                });

            modelBuilder.Entity("API.Entitites.WBEntities.IncomeDetail", b =>
                {
                    b.HasOne("API.Entitites.WBEntities.Income", "Income")
                        .WithMany("IncomeDetails")
                        .HasForeignKey("incomeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Income");
                });

            modelBuilder.Entity("API.Entitites.WBEntities.OrderDetail", b =>
                {
                    b.HasOne("API.Entitites.WBEntities.Order", "Order")
                        .WithMany()
                        .HasForeignKey("gNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Entitites.WBEntities.Income", "Income")
                        .WithMany()
                        .HasForeignKey("incomeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Income");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("API.Entitites.WBEntities.Sale", b =>
                {
                    b.HasOne("API.Entitites.WBEntities.OrderDetail", "OrderDetail")
                        .WithMany()
                        .HasForeignKey("odid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderDetail");
                });

            modelBuilder.Entity("API.Entitites.WBEntities.Income", b =>
                {
                    b.Navigation("IncomeDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
